// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"log/slog"
	"review_service/internal/biz"
	"review_service/internal/conf"
	"review_service/internal/data"
	"review_service/internal/server"
	"review_service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger *slog.Logger) (*kratos.App, func(), error) {
	registrar := server.NewRegistrar(registry)
	db, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(db, logger)
	if err != nil {
		return nil, nil, err
	}
	reviewRepo := data.NewReviewRepo(dataData, logger)
	reviewUsecase := biz.NewReviewUsecase(reviewRepo, logger)
	reviewService := service.NewReviewService(reviewUsecase)
	grpcServer := server.NewGRPCServer(confServer, reviewService)
	httpServer := server.NewHTTPServer(confServer, reviewService)
	app := newApp(logger, registrar, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
