server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s

data:
  database:
    driver: mysql
    source: "root:root1234@tcp(127.0.0.1:13306)/review_service?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 1s
    write_timeout: 1s
snowflake:
  start_time: "2026-01-01"
  machine_id: 1
